### ISSUE TITLE
Submit Document - D1

### ISSUE THREAD

**Issue by srowhani** [DankIdeaCentral/migrate-app#10]
Only one team member needs to submit this document via cuLearn by 09:00 AM September 26.
PDF only. File naming scheme: comp3004-d1_<project-name>.pdf (use - instead of space in file
names).
- [x] Completed

**Comment by bazadactyl** [comment]
I submitted the D1 proposal and the D1 slides through cuLearn.
I also sent an updated D0 directly to the professor using dankideacentral@gmail.com
