### ISSUE TITLE
Database transaction service

### ISSUE THREAD

**Issue by srowhani** [DankIdeaCentral/migrate-app#17]
Service or some other thing above the activity that can read / write / update the database.

**Comment by ermel272** [comment]
Gonna grab this one !

**Comment by srowhani** [comment]
Essentially all we really need to store is auth token. We might have to rethink this task. Could possibly be merged with SharedPreferences #30

**Comment by srowhani** [comment]
Also right now, twitter is authenticating using my consumer key / access token. One of the next steps is setting up the twitter authentication

**Comment by ermel272** [comment]
Want me to work on that? Or was it something you were already working on?

**Comment by ermel272** [comment]
@srowhani @basimr @zandermax If you guys are fine with it, I can close this if it is made irrelevant by #30
