### ISSUE TITLE
Implement startup functionality

### ISSUE THREAD

**Issue by srowhani** [DankIdeaCentral/migrate-app#19]
Determine, based on what auth tokens are available, what activity to route user to
- [ ] Store user token in `sharedPreferences`
- [ ] Read token, see if still valid (against twitter)
- [ ] Handle special cases
- [ ] Route to Activity of interest

**Comment by yourFavoriteSoftwareDeveloper** [comment]
it seems that Auth Tokens don't expire https://dev.twitter.com/oauth/overview/faq   -- search for "expire" -- just going to check if the token exists.
