### ISSUE TITLE
Create login activity

### ISSUE THREAD

**Issue by srowhani** [DankIdeaCentral/migrate-app#21]
Includes:
- [x] Setting up the view to include necessary UI elements
- [x] Wire in authentication (preferably with twitter4)
  - Currently auth tokens do not expire.
  - https://dev.twitter.com/oauth/overview/faq
  - http://twitter4j.org/en/code-examples.html#signinwithtwitter
- [x] Store the authentication token in SharedPreferences

**Comment by srowhani** [comment]
If we go with fabric:
https://code.tutsplus.com/tutorials/quick-tip-authentication-with-twitter-and-fabric--cms-23801

I think we could do better just implementing authentication with our own form and twitter4j

**Comment by ermel272** [comment]
Is this task the creation of the activity or hooking up the authentication logic as well?

**Comment by srowhani** [comment]
The auth implementation is included in this task. I'll specify sub-goals. @basimr

**Comment by srowhani** [comment]
I'm going to go ahead and close the other issue, writing to SharedPref is too small to be its own task imo.

https://developer.android.com/training/basics/data-storage/shared-preferences.html
