### ISSUE TITLE
Create Service to listen to Tweet Stream.

### ISSUE THREAD

**Issue by yourFavoriteSoftwareDeveloper** [DankIdeaCentral/migrate-app#42]
- [ ] Launch the service off of the TweetFeedActivity
- [ ] Set up the twitter stream off the service 
- [ ] Figure out the filtering for the location
- [ ] Initial setup of data structure to hold tweet counts for locations

**Comment by srowhani** [comment]
In case you might need it:
https://gist.github.com/srowhani/49ff5f76eb5c1046e8ff1821243df18d
