### ISSUE TITLE
Open TweetList Fragment on Cluster Click

### ISSUE THREAD

**Issue by yourFavoriteSoftwareDeveloper** [DankIdeaCentral/migrate-app#53]
- [x] Manage the change in fragments 
- [x] Set up list item view for Tweet Information
- [x] populate the list with tweets from the selected cluster

**Comment by srowhani** [comment]
When I made changes to TweetNode model, I also adjusted the ListAdapter. I'll leave it where it is, and push it for tomorrow morning
