### ISSUE TITLE
Add Directions Button to the TweetList Fragment

### ISSUE THREAD

**Issue by bazadactyl** [DankIdeaCentral/migrate-app#62]
From our functional requirements:

> The user must be able to view directions from their current location to nodes displayed on a map by being redirected to the Google Maps app.

**Comment by yourFavoriteSoftwareDeveloper** [comment]
Is it alright if I take over this task? I'm currently working in the TwitterListFragment.

**Comment by ermel272** [comment]
@zandermax Sure!
