### ISSUE TITLE
Draw Clusters Based on User's Followers

### ISSUE THREAD

**Issue by bazadactyl** [DankIdeaCentral/migrate-app#65]
From our functional requirements:

> The nodes must be sized and coloured. This will be based on: 
> - The density of Tweets originating from the node’s geolocation.
> - The number of Tweets coming from people the user follows.
> - The number of Tweets coming from people the user is followed by.

https://github.com/googlemaps/android-maps-utils/tree/master/library/src/com/google/maps/android/clustering

Modify algo to associate weight with nodes.

**Comment by srowhani** [comment]
```
private void changeBitmapColor(Bitmap sourceBitmap, ImageView image, int color) {

    Bitmap resultBitmap = Bitmap.createBitmap(sourceBitmap, 0, 0,
            sourceBitmap.getWidth() - 1, sourceBitmap.getHeight() - 1);
    Paint p = new Paint();
    ColorFilter filter = new LightingColorFilter(color, 1);
    p.setColorFilter(filter);
    image.setImageBitmap(resultBitmap);

    Canvas canvas = new Canvas(resultBitmap);
    canvas.drawBitmap(resultBitmap, 0, 0, p);
}
```

Something like this to add a color filter to a bitmap for NodeRenderer
