### ISSUE TITLE
Functional Properties

### ISSUE THREAD

**Issue by srowhani** [DankIdeaCentral/migrate-app#8]
- [x] Functional Properties of the system
- [x] Provide at least two user scenarios.
- [x] A description of the non-functional properties your system needs to support. There should be at least two of these. Justify why these properties are important for your system.

**Comment by ermel272** [comment]
For Thursday's meeting, I'm just gonna bring some small description of what I think the app needs to do. We can compare and create one app description from the 4 that we bring and then pull function requirements and use cases out of that.

**Comment by bazadactyl** [comment]
We finished this together on 2016-09-24.
Document is on Google Drive: https://docs.google.com/document/d/1FQNcGaDuKEp3ARz6C1I9nFQEN292ajTQM46aBsxkbiU/edit
