### ISSUE TITLE
Fix funky cluster icons

### ISSUE THREAD

**Issue by bazadactyl** [DankIdeaCentral/migrate-app#93]
## Issue
Tweet clusters on the map are functioning normally, but the icons seem to be rendering incorrectly. 

![screenshot_1478811153](https://cloud.githubusercontent.com/assets/9298270/20193827/c18672b2-a75d-11e6-8080-52681e4e0aee.png)

**Comment by srowhani** [comment]
What do you mean?

**Comment by bazadactyl** [comment]
Can you see the screenshot? It looks like the icons' colors are messed up.

**Comment by srowhani** [comment]
Part of the requirement was the coloring, so I added I modify the pixel argb when producing the bitmap

**Comment by srowhani** [comment]
We need to color the nodes unfortunately because of the requirements.
